version: '2'
services:
    db:
        container_name: balance_db
        image: postgres:9.5
        volumes:
            - balance_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=balance
            - POSTGRES_USER=balance
            - POSTGRES_DB=balance_db
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    balance_db: {}