# problems related to non UTF-8 files contained in this project
# see https://github.com/docker/compose/issues/5019
# on windows use the git bash
version: '2'
services:
    web:
      build: .
      ports:
          - 8080:8080
          - 9001:9001
      depends_on:
          - balance_db
    balance_db:
        container_name: balance_db
        image: postgres:9.5
        volumes:
            - balance_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=balance
            - POSTGRES_USER=balance
            - POSTGRES_DB=balance_db
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    creditlimit_db: {}